# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postimage',
            field=models.ImageField(default='http://4cdn.hu/kraken/image/upload/s--5Ni8VCBZ--/w_340/6r168HeddzIYmOW1s.jpeg', upload_to=''),
            preserve_default=False,
        ),
    ]
